package vistas;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import paneles.PanelAñadir;
import paneles.PanelDelete;
import paneles.PanelOtros;
import paneles.PanelSelect;

/**
 *
 * @author antonio minero
 */
public class FormUsuarioAdmin extends javax.swing.JFrame {

    PanelSelect panelSelect;
    PanelAñadir panelAñadir;
    PanelDelete panelDelete;
    PanelOtros panelOtros;
    
    //JTabbedPane pestañas;
    
    String palabra= "";

    public String getPalabra() {
        return palabra;
    }

    public void setPalabra(String palabra) {
        this.palabra = palabra;
    }
    
    
    /**
     * Creates new form FormUsuarioAdmin
     */
    public FormUsuarioAdmin() {
        this.setTitle("Logeado como administrador");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        initComponents();
    }
    
    public JLabel getjLabel1() {
        return jLabelAdminCode;
    }

    public void setjLabel1(String nuevoTexto) {
        jLabelAdminCode.setText("Codigo: "+nuevoTexto);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelAdminCode = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAdminCode.setText("jLabelAdminCode");

        jButtonLogout.setText("LOGOUT");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelAdminCode))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButtonLogout)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelAdminCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        //Enviamos datos al servidor para que sepas que hemos cerrado sesion
         try {
            //IMPLEMENTA
            Socket socket = new Socket("localhost", 8888);//***Poner el metodo get del campo de texto de IPServidor

            // Obtener flujos de entrada y salida.
            BufferedReader lector = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            BufferedWriter escriptor = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));

            // Aquí enviamos la señal de "logout" al servidor.
            String logoutSignal = "exit";
            escriptor.write(logoutSignal);
            escriptor.newLine();
            escriptor.flush();

            // Resto de la lógica de cierre de sesión.
            lector.close();
            escriptor.close();
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }       
        palabra = "exit";

        //Cerramos ventana actual y abrimos la principal
        this.setVisible(false);
        
        MainForm mainForm = new MainForm();
        mainForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mainForm.setLocation(mainForm.getX(),mainForm.getY()); 
        mainForm.setVisible(true);     
        mainForm.setPalabra(palabra);
        
        
        JOptionPane.showMessageDialog(null,"Palabra: "+ palabra+"Palabra: "+mainForm.getPalabra());
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabelAdminCode;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
